import Head from 'next/head'
import { useQuery } from 'react-query'
import { DefaultApi } from '../openapi'
import dammyTodos from '../mock-data/todo.json'

export default function Home() {
  const api = new DefaultApi({
    basePath: 'http://localhost:3000',
  })

  const { data: todos = dammyTodos } = useQuery('todos', async () => {
    const { data } = await api.todosControllerFindAll()
    return data
  })

  const stillTodos = todos.filter((todo) => !todo.done)
  const doneTodos = todos.filter((todo) => todo.done)

  return (
    <div className='bg-purple-100 min-h-screen'>
      <Head>
        <title>くわログ</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div className='max-w-4xl w-full mx-auto px-4'>
          <h1 className='pt-8 text-6xl font-bold'>Kuwa Todo</h1>
          <div className='grid sm:grid-cols-2 gap-8 mt-8'>
            <div className='bg-white rounded-sm shadow px-4 py-2 h-96'>
              {stillTodos.map((todo, index: number) => (
                <div className='bg-purple-100 rounded-sm flex items-center my-2 px-2 py-3' key={index}>
                  <div className='mr-2'>□</div>
                  <div>{todo.title}</div>
                </div>
              ))}
            </div>
            <div className='bg-white rounded-sm shadow px-4 py-2 h-96'>
              {doneTodos.map((todo, index: number) => (
                <div className='bg-green-100 rounded-sm flex items-center my-2 px-2 py-3' key={index}>
                  <div className='mr-2'>☑︎</div>
                  <div>{todo.title}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
